[build]
  command = "npm i && cd frontend && npm i && npm run build"
  publish = "frontend/dist"

[template.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""
  SUPABASE_SERVICE_ROLE = ""
  MAIL_HOST = ""
  MAIL_PORT= ""
  MAIL_USER = ""
  MAIL_PASS = ""
  MAIL_FROM = "example@supaup.com"
  MAX_NOTIFICATIONS_PER_RUN = 3
  MAX_SITE_CHECKS_PER_RUN = 10

[dev]
  base = "frontend"
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "functions/"
  included_files = ["package.json"]