[build]
  command = "npm i && cd frontend && npm i && npm run build"
  publish = "frontend/dist"

[dev]
  base = "frontend"
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "functions/"
  included_files = ["package.json"]