[build]
  base = "frontend/"
  command = "npm run build"
  publish = "dist"

[dev]
  base = "frontend/"
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "functions/"